// MODAL
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const EDIT_MODAL = 'EDIT_MODAL'

// ANNOTATION
export const DELETE_ANNOTATION = 'DELETE_ANNOTATION'
export const INSERT_ANNOTATION = 'INSERT_ANNOTATION'